// makefile.go
//
// Generates a Makefile in the generated admin panel application with targets
// that run every step required to build the dashboard binary: building the
// Tailwind CSS, regenerating the sqlc queries and templ views, tidying the Go
// module and compiling the binary. No npm/node is required — Tailwind CSS runs
// via the standalone binary (TAILWIND override + optional get-tailwind
// download) and Chart.js is vendored at generation time.
package generator

import (
	"os"
	"path/filepath"
)

// tailwindStandaloneVersion is the pinned Tailwind CSS standalone release used
// by the generated Makefile's get-tailwind target.
const tailwindStandaloneVersion = "v3.4.19"

// generateMakefile writes a Makefile into the output directory. The default
// target builds the dashboard binary from scratch; the individual steps are
// also exposed as separate targets (css, sqlc, templ, tidy, get-tailwind) so
// they can be re-run on their own. The binary is named after the output
// directory base name (matching the module name written to go.mod).
// Returns an error on write failure.
func (g *Generator) generateMakefile() error {
	binary := filepath.Base(g.OutDir)
	makefile := `# Makefile generated by YAGA — builds the dashboard binary and its assets.
# Usage: run "make" (or "make build") inside this directory.

# Binary name (module name of the generated project).
BINARY := ` + binary + `

# Listen port for the dashboard (passed to the binary as --port).
PORT ?= 8080

# Log level for the dashboard (passed to the binary as --log): full or err.
LOG ?= full

# Tailwind CSS standalone binary. Defaults to "tailwindcss" on PATH; point it
# at the binary downloaded by the get-tailwind target to build without a JS
# toolchain:
#   make TAILWIND=$(CURDIR)/.tools/tailwindcss css
TAILWIND ?= tailwindcss

# Pinned Tailwind CSS standalone release used by the get-tailwind target.
TAILWIND_VERSION ?= ` + tailwindStandaloneVersion + `

# Release archive name (binary name + date stamp). Override to customize:
#   make package PACKAGE_NAME=my-release
PACKAGE_NAME ?= $(BINARY)-$(shell date +%Y%m%d)

.PHONY: all build css sqlc templ tidy get-tailwind run package clean

all: build

# Build the dashboard binary and its assets (default target).
build: css sqlc templ
	go build -o $(BINARY) .

# Build the Tailwind CSS into static/css/styles.css. Chart.js is already
# vendored into static/js/chart.js at generation time — no JS toolchain step.
css:
	$(TAILWIND) -i ./internal/assets/css/styles.css -o ./static/css/styles.css --minify

# Download the Tailwind CSS standalone binary for this OS/arch (linux/macos x
# x64/arm64; Windows is not supported) into .tools/ so the dashboard builds
# with only the Go toolchain plus this single binary.
get-tailwind:
	mkdir -p .tools
	@case "$$(uname -s)-$$(uname -m)" in \
	  Linux-x86_64) file=tailwindcss-linux-x64 ;; \
	  Linux-aarch64|Linux-arm64) file=tailwindcss-linux-arm64 ;; \
	  Darwin-x86_64) file=tailwindcss-macos-x64 ;; \
	  Darwin-arm64) file=tailwindcss-macos-arm64 ;; \
	  *) echo "Unsupported platform: $$(uname -s)-$$(uname -m)"; exit 1 ;; \
	esac; \
	echo "Downloading tailwindcss $(TAILWIND_VERSION) ($$file)..." ; \
	curl -sL -o .tools/tailwindcss "https://github.com/tailwindlabs/tailwindcss/releases/download/$(TAILWIND_VERSION)/$$file" ; \
	chmod +x .tools/tailwindcss ; \
	echo "Downloaded .tools/tailwindcss" ; \
	echo "Next: make TAILWIND=$(CURDIR)/.tools/tailwindcss css"

# Regenerate the sqlc query code into internal/data.
sqlc:
	sqlc generate

# Compile the .templ views into *_templ.go (required before go build).
# Tidy first so the toolchain can resolve and download templ.
templ: tidy
	go tool templ generate

# Tidy the Go module dependencies.
tidy:
	go mod tidy

# Build and run the dashboard server.
run: build
	./$(BINARY) --port $(PORT) --log $(LOG)

# Package the binary and every file the dashboard needs at runtime (static
# assets incl. uploads, sql/ migrations and the sqlite data/ dir when present)
# into a tar.gz archive for deployment. Extract it on the target machine and
# run the binary from the extracted directory (the sqlite DSN is relative).
package: build
	rm -rf $(PACKAGE_NAME)
	mkdir -p $(PACKAGE_NAME)
	cp -r $(BINARY) static $(PACKAGE_NAME)/
	for d in sql data; do if [ -d $$d ]; then cp -r $$d $(PACKAGE_NAME)/; fi; done
	tar czf $(PACKAGE_NAME).tar.gz $(PACKAGE_NAME)
	rm -rf $(PACKAGE_NAME)

# Remove the built binary and any release archive.
clean:
	rm -f $(BINARY) $(PACKAGE_NAME).tar.gz
`
	return os.WriteFile(filepath.Join(g.OutDir, "Makefile"), []byte(makefile), 0644)
}
