// makefile.go
//
// Generates a Makefile in the generated admin panel application with targets
// that run every step required to build the dashboard binary: compiling the
// templ views, tidying the Go module and compiling the binary. No npm/node, no
// sqlc and no Tailwind are required — the schema comes from the config's
// captured `schema:` block, the pre-built stylesheet is vendored at generation
// time, and Chart.js is embedded into the yaga binary, so the build runs fully
// offline.
package generator

import (
	"os"
	"path/filepath"
)

// generateMakefile writes a Makefile into the output directory. The default
// target builds the dashboard binary from scratch; the individual steps are
// also exposed as separate targets (templ, tidy) so they can be re-run on
// their own. The binary is named after the output directory base name
// (matching the module name written to go.mod).
// Returns an error on write failure.
func (g *Generator) generateMakefile() error {
	binary := filepath.Base(g.OutDir)
	makefile := `# Makefile generated by YAGA — builds the dashboard binary and its assets.
# Usage: run "make" (or "make build") inside this directory.
# No npm/node, no sqlc and no Tailwind are required: the stylesheet is
# pre-built and vendored into static/css/styles.css at generation time, Chart.js
# is embedded in the binary, and the schema comes from the config's captured
# ` + "`schema:`" + ` block.

# Binary name (module name of the generated project).
BINARY := ` + binary + `

# Listen port for the dashboard (passed to the binary as --port).
PORT ?= 8080

# Log level for the dashboard (passed to the binary as --log): full or err.
LOG ?= full

# Release archive name (binary name + date stamp). Override to customize:
#   make package PACKAGE_NAME=my-release
PACKAGE_NAME ?= $(BINARY)-$(shell date +%Y%m%d)

.PHONY: all build templ tidy run package clean

all: build

# Build the dashboard binary and its assets (default target). The CSS is
# pre-built and vendored at generation time, so there is no css/get-tailwind
# step anymore.
build: templ
	go build -o $(BINARY) .

# Compile the .templ views into *_templ.go (required before go build).
# Tidy first so the toolchain can resolve and download templ.
templ: tidy
	go tool templ generate

# Tidy the Go module dependencies.
tidy:
	go mod tidy

# Build and run the dashboard server.
run: build
	./$(BINARY) --port $(PORT) --log $(LOG)

# Package the binary and every file the dashboard needs at runtime (static
# assets incl. uploads, the .ENV database config, sql/ migrations and the
# sqlite data/ dir when present) into a tar.gz archive for deployment. Extract
# it on the target machine and run the binary from the extracted directory (the
# sqlite DSN is relative); edit .ENV to point at the deployment database.
package: build
	rm -rf $(PACKAGE_NAME)
	mkdir -p $(PACKAGE_NAME)
	cp -r $(BINARY) static $(PACKAGE_NAME)/
	if [ -f .ENV ]; then cp .ENV $(PACKAGE_NAME)/; fi
	for d in sql data; do if [ -d $$d ]; then cp -r $$d $(PACKAGE_NAME)/; fi; done
	tar czf $(PACKAGE_NAME).tar.gz $(PACKAGE_NAME)
	rm -rf $(PACKAGE_NAME)

# Remove the built binary and any release archive.
clean:
	rm -f $(BINARY) $(PACKAGE_NAME).tar.gz
`
	return os.WriteFile(filepath.Join(g.OutDir, "Makefile"), []byte(makefile), 0644)
}
